import type { Metadata } from 'next'
import { Suspense } from 'react'

import { Footer, Loader } from '@/components'
import '@/lib/fontawesome'
import './globals.css'
import Renderer from './Renderer'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body>
				<Suspense fallback={<Loader />}>
					<Renderer>{children}</Renderer>
				</Suspense>
				<Footer />
			</body>
		</html>
	)
}

// // Artificial delay component to test Suspense
// async function SlowComponent({ children }: { children: React.ReactNode }) {
// 	await new Promise((resolve) => setTimeout(resolve, 3000)) // 3 second delay
// 	return <>{children}</>
// }
