import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import { Navigation, SecondNav } from '@/components'
import { getPageHierarchy } from '@/lib/contentful/client'
import './globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	const pages = await getPageHierarchy()

	// console.log(pages[0].fields.children)
	return (
		<html lang="en">
			<body>
				<header className="bg-white shadow-sm">
					<div className="max-w-7xl mx-auto px-4 py-4">
						<Navigation pages={pages} />
					</div>
				</header>
				<main>
					<div className="mb-[3.1rem] md:mb-16"></div>
					<SecondNav pages={pages} />
					{children}
				</main>
			</body>
		</html>
	)
}
